### ISSUE TITLE
Getting basic states from probabilities

### ISSUE THREAD

**Issue by renderit** [gvanderheide/discreteMarkovChain#14]
Hi, great work here! I'm working on a simple problem and would love your feedback. Essentially, I have these States or "buttons". I have let's say initial probabilities, of a user going from one button to another. After time t1, I want to know which button he "could" be on now(or predict). After every time 't' he presses a some button button, we update the transition matrix and predict the next button. Sounds simple I'm having a hard time incorporating this with the library.. Here's a screenshot for your reference:
![untitled diagram 1](https://user-images.githubusercontent.com/8347939/27935748-b55a05e8-6261-11e7-951d-b34312afb2c1.png)

**Comment by gvanderheide** [comment]
Dear renderit,

I don't think you should open issues to get feedback about a problem. 

It is unclear to me what you want to do exactly. I'm confused by several things:
-What does updating the transition matrix mean? Can the transition matrix change over time?
-It is discrete time or continuous time?
-Why do the probabilities add up to more than 1 for some buttons?

Calculating where you are 'n' periods from now is usually a matter of calculating p_n = p_{n-1}P, with p_0 the initial distribution.  

I'm going to close this since it's not an actual issue.
